### ISSUE TITLE
opentracing and grpci raises exception

### ISSUE THREAD

**Issue by goern** [goern/thoth-stub-api#1]
When using grpcio > 1.17.1 and grpcio-opentracing an exception is raised:
```
2019-04-03 10:19:52,455 [24765] INFO     root:126: Logging to a Sentry instance is turned off
2019-04-03 10:19:52,455 [24765] INFO     root:148: Logging to rsyslog endpoint is turned off
2019-04-03 10:19:52,455 [24765] INFO     stub:54: This is Stub gRPC server v0.1.0
2019-04-03 10:19:52,455 [24765] INFO     jaeger_tracing:419: Initializing Jaeger Tracer with UDP reporter
2019-04-03 10:19:52,456 [24765] INFO     jaeger_tracing:360: Using sampler ConstSampler(True)
2019-04-03 10:19:52,593 [24765] INFO     jaeger_tracing:409: opentracing.tracer initialized to <jaeger_client.tracer.Tracer object at 0x7f0b1c4f57b8>[app_name=stub_api]
2019-04-03 10:19:55,319 [24765] INFO     jaeger_tracing:73: Reporting span b3c28614132f226a:b3c28614132f226a:0:1 stub_api./stub.Stub/Info
2019-04-03 10:19:55,320 [24765] ERROR    grpc._server:401: Exception calling application: Can't instantiate abstract class _OpenTracingServicerContext with abstract methods abort_with_status
Traceback (most recent call last):
  File "/home/goern/.local/share/virtualenvs/stub-api-U-8IB0ql/lib/python3.6/site-packages/grpc/_server.py", line 393, in _call_behavior
    return behavior(argument, context), True
  File "/home/goern/.local/share/virtualenvs/stub-api-U-8IB0ql/lib/python3.6/site-packages/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    _UnaryServerInfo(self._method), handler)
  File "/home/goern/.local/share/virtualenvs/stub-api-U-8IB0ql/lib/python3.6/site-packages/grpc_opentracing/_server.py", line 145, in intercept_unary
    servicer_context, span)
TypeError: Can't instantiate abstract class _OpenTracingServicerContext with abstract methods abort_with_status
^C2019-04-03 10:19:59,534 [24765] INFO     jaeger_tracing:178: Span publisher exited

```

**Comment by goern** [comment]
see upstream issue: https://github.com/opentracing-contrib/python-grpc/issues/20
